name: 'Tests'

on:
  push:
    paths:
      - '.github/**/*'
      - '**/*.vue'
      - '**/*.ts'
      - '**/*.js'
      - '*.ts'
      - '*.js'
      - '*.json'
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['18.x']
    name: Node ${{ matrix.node }}

    steps:
      - uses: actions/checkout@v3
      - uses: arduino/setup-task@v1
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - run: npm install
      - run: |
          cat > .firebase.config.json << "EOF"
            {
              "apiKey": "${{ secrets.TOGOWL_API_KEY }}",
              "authDomain": "togowl.firebaseapp.com",
              "databaseURL": "https://togowl.firebaseio.com",
              "projectId": "togowl",
              "storageBucket": "togowl.appspot.com",
              "messagingSenderId": "505439731265",
              "appId": "1:505439731265:web:e8dfd007733f97471c50c0"
            }
          EOF
      - run: task build

      - run: task test-with-coverage
      - uses: codecov/codecov-action@v3
        if: "matrix.node == '18.x' && success()"
        with:
          file: ./coverage/clover.xml

      - name: "Discord notification (not success)"
        uses: rjstone/discord-webhook-notify@v1
        if: "! success()"
        with:
          description: "⚠ Togowl Tests failed!"
          footer: "Node.js v18"
          severity: error
          avatarUrl: https://cdn.otamart.com/item-picture/26205822/0-1574353123758.jpg
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

  notify:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: "Discord notification (success)"
        uses: rjstone/discord-webhook-notify@v1
        if: always()
        with:
          description: "✅ Togowl Tests passed!"
          footer: "Node.js v18"
          severity: info
          avatarUrl: https://cdn.otamart.com/item-picture/26205822/0-1574353123758.jpg
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
